[workspace]
resolver = "3"
members = ["jevmalloc", "jevmalloc-sys"]
default-members = ["jevmalloc", "jevmalloc-sys"]

[workspace.package]
authors = ["Jason Volk <jason@zemos.net>", "June August <june@girlboss.ceo>"]
categories = ["memory-management", "api-bindings"]
description = "Rust allocator wrapping jemalloc."
documentation = "https://github.com/matrix-construct/jevmalloc"
edition = "2024"
homepage = "https://github.com/matrix-construct/jevmalloc"
keywords = ["allocator", "jemalloc"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/matrix-construct/jevmalloc"
version = "0.0.0+5.3.1-2-gee054313a33bef077b946fe744adae423b1a1b4f"

[workspace.dependencies]
arrayvec = { version = "0", default-features = false }
cc = "1"
jevmalloc = { version = "0.0.0", path = "jevmalloc", default-features = false }
jevmalloc-sys = { version = "0.0.0", path = "jevmalloc-sys", default-features = false }
libc = { version = "0.2", default-features = false }
paste = "1"
rustflags = "0.1"

[workspace.lints.rust]
absolute_paths_not_starting_with_crate = "warn"
deprecated_in_future = "warn"
elided_lifetimes_in_paths = "warn"
explicit_outlives_requirements = "warn"
ffi_unwind_calls = "warn"
keyword_idents = { level = "warn", priority = -1 }
macro_use_extern_crate = "warn"
meta_variable_misuse = "warn"
missing_abi = "warn"
missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
missing_docs = "warn"
missing_unsafe_on_extern = "warn"
non_ascii_idents = "warn"
rust_2021_incompatible_closure_captures = "warn"
rust_2021_incompatible_or_patterns = "warn"
rust_2021_prefixes_incompatible_syntax = "warn"
rust_2021_prelude_collisions = "warn"
single_use_lifetimes = "warn"
trivial_casts = "warn"
unit_bindings = "warn"
unreachable_pub = "warn"
unsafe_op_in_unsafe_fn = "warn"
unstable_features = "warn"
unused_extern_crates = "warn"
unused_import_braces = "warn"
unused_lifetimes = "warn"
unused_macro_rules = "warn"

# some sadness
unexpected_cfgs = "allow"
unsafe_code = "allow"
unused_crate_dependencies = "allow"

[workspace.lints.clippy]
as_underscore = "warn"
assertions_on_result_states = "warn"
cargo = { level = "warn", priority = -1 }
cast_possible_truncation = "warn"
cast_possible_wrap = "warn"
cast_sign_loss = "warn"
complexity = { level = "warn", priority = -1 }
correctness = { level = "warn", priority = -1 }
dbg_macro = "warn"
default_union_representation = "warn"
deref_by_slicing = "warn"
doc_markdown = "warn"
empty_drop = "warn"
empty_structs_with_brackets = "warn"
exit = "warn"
filetype_is_file = "warn"
float_cmp_const = "warn"
format_push_string = "warn"
get_unwrap = "warn"
if_not_else = "warn"
if_then_some_else_none = "warn"
impl_trait_in_params = "warn"
implicit_clone = "warn"
let_underscore_untyped = "warn"
lossy_float_literal = "warn"
mem_forget = "warn"
missing_docs_in_private_items = "warn"
missing_errors_doc = "warn"
missing_panics_doc = "warn"
multiple_unsafe_ops_per_block = "warn"
mutex_atomic = "warn"
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
pub_without_shorthand = "warn"
rc_buffer = "warn"
rc_mutex = "warn"
redundant_type_annotations = "warn"
semicolon_outside_block = "warn"
str_to_string = "warn"
string_lit_chars_any = "warn"
style = { level = "warn", priority = -1 }
suspicious = { level = "warn", priority = -1 }
suspicious_xor_used_as_pow = "warn"
tests_outside_test_module = "warn"
too_long_first_doc_paragraph = { level = "warn", priority = -11 }
try_err = "warn"
undocumented_unsafe_blocks = "warn"
unnecessary_safety_comment = "warn"
unnecessary_safety_doc = "warn"
unnecessary_self_imports = "warn"
unneeded_field_pattern = "warn"
unseparated_literal_suffix = "warn"
verbose_file_reads = "warn"

# some sadness
arithmetic_side_effects = "allow"
as_conversions = "allow"
collapsible_if = { level = "allow", priority = 1 }
inline_always = { level = "allow", priority = 1 }
map_unwrap_or = { level = "allow", priority = 1 }
missing_const_for_fn = { level = "allow", priority = 1 }
obfuscated_if_else = { level = "allow", priority = 1 }
option_if_let_else = { level = "allow", priority = 1 }
similar_names = { level = "allow", priority = 1 }
single_match_else = { level = "allow", priority = 1 }
struct_field_names = { level = "allow", priority = 1 }
unreadable_literal = { level = "allow", priority = 1 }
